services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: chmod +x ffmpeg/ffmpeg && pip install -r requirements.txt
    startCommand: gunicorn app:app
    branch: main # or your default branch name
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true